#!/data/data/com.termux/files/usr/bin/bash
# Licenced under GNU GPL 3.0
# Fork of some generic shell script(i forgot the name lol)
# I stylized it to look a bit better
# By StarFromTheSky

# script to download youtube videos to mp3,m4a,mp4

# Usage
# install ternux and setup the tool 
# for simplicity converting to mp3 is done by pressing enter after shering video to termux
clear
echo
figlet 1CLICK | lolcat
echo
echo "(1) Download as MP3"
echo "(2) Download as MP4a"
echo "(3) Download the video with 360p resolution"
echo "(4) Download the video with 480p resolution"
echo "(5) Download the video with 720p resolution"
echo "(6) Download the video with 1080p resolution"
echo Please type any number:

command='-no-mtime -o /data/data/com.termux/files/home/storage/shared/Movies/%(title)s.%(ext)s -f'
read option

if [ "$option" -eq "1" ]
then
    clear
    echo "--no-mtime -o /data/data/com.termux/files/home/storage/shared/Music/%(title)s.%(ext)s -x --audio-format mp3 --audio-quality 320K --prefer-ffmpeg" > ~/.config/youtube-dl/config
    youtube-dl $1
elif [ "$option" -eq "2" ]
then
    clear
    echo "-no-mtime -o /data/data/com.termux/files/home/storage/shared/Music/%(title)s.%(ext)s -f 140" > ~/.config/youtube-dl/config
    youtube-dl $1
elif [ "$option" -eq "3" ]
then
    clear
    echo "$command \"best[height<=360]\"" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "4" ]
then
    clear
    echo "$command \"best[height<=480]\"" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "5" ]
then
    clear
    echo "$command \"best[height<=720]\"" > ~/.config/youtube-dl/config
    youtube-dl $1

elif [ "$option" -eq "6" ]
then
    clear
    echo "$command \"best[height<=1080]\"" > ~/.config/youtube-dl/config
    youtube-dl $1
fi
